### ISSUE TITLE
Add Matrix Chat Support

### ISSUE THREAD

**Issue by Nic-Wow1** [Billy-S/blockysurvival#10] opened 2018-09-16 22:03 UTC
**Feature**: Add Matrix as a chatting option alongside currently supported Discord and IRC.

**How**: Utilizing the Matrix Bridges

Discord Bridge: https://t2bot.io/discord/

IRC Bridge: https://matrix.org/docs/projects/as/irc-bridge.html

Matrix Communities for Multiple Channels: https://medium.com/@RiotChat/communities-aka-groups-are-here-announcing-riot-web-0-13-riot-ios-0-6-and-riot-android-0-7-4-933cb193a28e

**Comment by luk3yx** [comment] 2018-09-16 22:08
Hello,

Last time I tried running Matrix, I couldn't get the main server running, let alone a bridge. It was probably a `ufw` rule blocking it, I'll have to remember to check next time.

Why should someone invest time in a Matrix server when there is already a viable and open alternative?

Thanks,

luk3yx

**Comment by Nic-Wow1** [comment] 2018-09-16 22:14
> Why should someone invest time in a Matrix server when there is already a viable and open alternative?

@luk3yx IRC is text only. So, now emojis or chat.
 If time is what you need help with, I can help you set it up. It is very easy to use.

Discord doesn't have this issue but is proprietary.

> Also, there doesn't need to be a Discord/Matrix bridge, it can use the existing IRC/Discord one.
As to why use the reason that you may want the Discord/Matrix bridge is for voice chat support. Personally, I have only used t with chat but i have heard of other servers using this feature.

If this isn't an issue for you then, the IRC/Matrix bridges is probably better.

**Comment by luk3yx** [comment] 2018-09-16 23:09
@Nic-Wow1 I get the following error when trying to run Matrix:

~~~
twisted - 131 - ERROR - - sqlite3.OperationalError: table event_reports already exists
~~~

It is supposedly caused by Python having an outdated sqlite, but I can't find where to upgrade it.

**Comment by Nic-Wow1** [comment] 2018-09-17 15:58
@luk3yx Are you using this script: https://matrix.org/docs/projects/client/weechat.html

**Comment by luk3yx** [comment] 2018-09-17 18:21
It's what version Python has that's the problem. That issue is with installing Synapse (the Matrix homeserver), not with WeeChat.

**Comment by Billy-S** [comment] 2018-09-17 18:22
Email spam alert

**Comment by luk3yx** [comment] 2018-09-17 18:22
> Email spam alert

Oh, sorry.

**Comment by Nic-Wow1** [comment] 2018-09-17 19:36
@luk3yx I still need what OS you are using and what Python version.

**Comment by luk3yx** [comment] 2018-09-17 19:37
> @luk3yx I still need what OS you are using and what Python version.

Ubuntu Server 18.04 LTS, Python 2.7.15rc1 (Matrix really should use Python3).

**Comment by Nic-Wow1** [comment] 2018-09-17 19:45
@luk3yx Please consider making an issue request for this:  https://github.com/matrix-org/synapse/issues

It will help other that may also have this issue.

**Comment by Nic-Wow1** [comment] 2018-09-22 22:15
@luk3yx Probably the easiest way to set this up anyway would be probably be through the RIOT client.
If you are open to installing something besides Weechat.

RIOT Bridge Info/Tutorial: https://about.riot.im/apps-bots-and-bridges/
Install RIOT: https://riot.im/desktop.html

**Comment by luk3yx** [comment] 2018-09-22 22:17
@Nic-Wow1 I need to set up the Matrix/IRC bridge, and I'd rather do it on the same server as IRC for latency.

**Comment by Nic-Wow1** [comment] 2018-09-24 19:33
Hmmmm, I would advise you to try joining the chat for IRC bridges? They have lots of people there that may be able to better help you. I have only used the RIOT client.

Chat URL: https://matrix.to/#/!SudviOJlimDvrGdFCY:matrix.org

**Comment by luk3yx** [comment] 2018-09-24 19:41
@Nic-Wow1 I am not interested in using Matrix myself, I just wanted to try running a xeroxIRC bridge.

Because the Freenode bridge exists, I'll close this, if you want a xeroxIRC or more direct bridge, re-open it.

**Closed by luk3yx** 2018-09-24 19:41 UTC
